Controllers/ShoppingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SoftNET_Project.Data;
using SoftNET_Project.Models;

using System.Net.Http;
using Microsoft.AspNetCore.Authorization;

using ClosedXML.Excel;
using System.IO;
using Newtonsoft.Json;
using System.Security.Claims;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Office2010.Excel;
using System.Xml;

namespace SoftNET_Project.Controllers
{
    public class ShoppingsController : Controller
    {
        private readonly SystemContext _context;
        public ShoppingsController(SystemContext context) => _context = context;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            User user = _context.Users.FirstOrDefault(i => i.NickName == User.Identity.Name);
            ViewBag.Wishlist = _context.Products.Include(p => p.Wishlist).ThenInclude(i => i.User).Where(i => i.Wishlist.Any(a => a.UserId == user.ID));
            ViewBag.Carts = _context.Products.Include(p => p.Carts).ThenInclude(i => i.User).Where(i => i.Carts.Any(a => a.UserId == user.ID));

            return View(await _context.Products.ToListAsync());
        }


        

        public IActionResult Wishlist()
        {
            var user = _context.Users.FirstOrDefault(u => u.NickName == User.Identity.Name);
            ViewBag.Wishlist = _context.Products.Include(p => p.Wishlist).ThenInclude(i => i.User).Where(i => i.Wishlist.Any(a => a.UserId == user.ID));

            return View();
        }

        public IActionResult Carts()
        {
            var user = _context.Users.FirstOrDefault(u => u.NickName == User.Identity.Name);
            ViewBag.Carts = _context.Products.Include(p => p.Carts).ThenInclude(i => i.User).Where(i => i.Carts.Any(a => a.UserId == user.ID));

            string tcmb = "https://www.tcmb.gov.tr/kurlar/today.xml";
            var xmlFile = new XmlDocument();
            xmlFile.Load(tcmb);
            ViewBag.dolar = Convert.ToDouble(xmlFile.SelectSingleNode("Tarih_Date/Currency[@Kod='USD']/BanknoteSelling").InnerXml);
            ViewBag.euro = Convert.ToDouble(xmlFile.SelectSingleNode("Tarih_Date/Currency[@Kod='EUR']/BanknoteSelling").InnerXml);
            ViewBag.pound = Convert.ToDouble(xmlFile.SelectSingleNode("Tarih_Date/Currency[@Kod='GBP']/BanknoteSelling").InnerXml);


            return View();
        }

        public IActionResult Purchased() {
            var user = _context.Users.FirstOrDefault(u => u.NickName == User.Identity.Name);
            ViewBag.Purchaseds = _context.Products.Include(p => p.Purchaseds).ThenInclude(i => i.User).Where(i => i.Purchaseds.Any(a => a.UserId == user.ID));

            return View(); 
        }


        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.ID == id);
        }




        // Data Controls

        [HttpPost, ActionName("AddWish")]
        public IActionResult AddWish(int id)
        {
            int userId = _context.Users.FirstOrDefault(i => i.NickName == User.Identity.Name).ID;
            User user = _context.Users.Include(i => i.Wishlists).First(i => i.NickName == User.Identity.Name);

            ICollection<UserWishlist> wishlists = user.Wishlists;
            wishlists.Add(new UserWishlist
            {
                UserId = userId,
                ProductId = id
            });

            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpPost, ActionName("AddCart")]
        public IActionResult AddCart(int id)
        {
            int userId = _context.Users.FirstOrDefault(i => i.NickName == User.Identity.Name).ID;
            User user = _context.Users.Include(i => i.Carts).First(i => i.NickName == User.Identity.Name);

            ICollection<UserCarts> carts = user.Carts;
            carts.Add(new UserCarts
            {
                UserId = userId,
                ProductId = id
            });

            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("RemoveWish")]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveWish(int id)
        {
            int userId = _context.Users.FirstOrDefault(i => i.NickName == User.Identity.Name).ID;
            User user = _context.Users.Include(i => i.Wishlists).First(i => i.NickName == User.Identity.Name);

            ICollection<UserWishlist> wishlists = user.Wishlists;
            wishlists.Remove(wishlists.FirstOrDefault(i => i.UserId == userId && i.ProductId == id));

            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpPost, ActionName("RemoveCart")]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveCart(int id)
        {
            int userId = _context.Users.FirstOrDefault(i => i.NickName == User.Identity.Name).ID;
            User user = _context.Users.Include(i => i.Carts).First(i => i.NickName == User.Identity.Name);

            ICollection<UserCarts> carts = user.Carts;
            carts.Remove(carts.FirstOrDefault(i => i.UserId == userId && i.ProductId == id));

            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost, ActionName("RemoveCartFromYourCarts")]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveCartFromYourCarts(int id)
        {
            int userId = _context.Users.FirstOrDefault(i => i.NickName == User.Identity.Name).ID;
            User user = _context.Users.Include(i => i.Carts).First(i => i.NickName == User.Identity.Name);

            ICollection<UserCarts> carts = user.Carts;
            carts.Remove(carts.FirstOrDefault(i => i.UserId == userId && i.ProductId == id));

            _context.SaveChanges();
            return RedirectToAction("Carts");
        }


        [HttpPost, ActionName("RemoveAllWishes")]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveAllWishes()
        {
            User user = _context.Users.Include(i => i.Wishlists).First(i => i.NickName == User.Identity.Name);

            ICollection<UserWishlist> wishlists = user.Wishlists;
            foreach (var item in wishlists)
            {
                wishlists.Remove(item);
            }

            _context.SaveChanges();
            return RedirectToAction("Wishlist");
        }


        [HttpPost, ActionName("RemoveAllCarts")]
        public IActionResult RemoveAllCarts()
        {
            User user = _context.Users.Include(i => i.Carts).First(i => i.NickName == User.Identity.Name);

            ICollection<UserCarts> carts = user.Carts;
            foreach (var item in carts)
            {
                carts.Remove(item);
            }

            _context.SaveChanges();
            return RedirectToAction("Carts");
        }


        [HttpPost, ActionName("Buy")]
        public IActionResult Buy()
        {


            int userId = _context.Users.FirstOrDefault(i => i.NickName == User.Identity.Name).ID;
            User userForCarts = _context.Users.Include(i => i.Carts).First(i => i.NickName == User.Identity.Name);
            User userForPurchased = _context.Users.Include(i => i.Purchaseds).First(i => i.NickName == User.Identity.Name);

            ICollection<UserCarts> carts = userForCarts.Carts;
            ICollection<UserPurchased> purchaseds = userForCarts.Purchaseds;

            foreach (var item in carts)
            {
                purchaseds.Add(new UserPurchased
                {
                    UserId = item.UserId,
                    ProductId = item.ProductId,
                });
                _context.Products.FirstOrDefault(i => i.Id == item.ProductId).Count--;
                carts.Remove(item);
            }

            _context.SaveChanges();
            return RedirectToAction("Carts");
        }
    }
}

Views/Shoppings/Carts.cshtml
@model SoftNET_Project.Models.User;
@{
    ViewData["Title"] = "Carts";

    double Total = 0;
    foreach (var mon in ViewBag.Carts)
    {
        Total += mon.Price;
    }
    double dollar = Total / ViewBag.dolar;
    double euro = Total / ViewBag.euro;
    double pound = Total / ViewBag.pound;
}

<div class="card mb-4 mt-2">
    <div class="card-body">
        <h1>Your Carts</h1>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Your Carts
    </div>
    <div class="card-body">
        <table id="sample_table" class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>
                        Product Name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Barcode
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.Carts)
                {
                    <tr>
                        <td>
                            <form asp-action="RemoveCartFromYourCarts" asp-route-id="@item.Id" method="post">
                                <button class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                            </form>
                        </td>
                        <td>
                            <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">@item.ProductName</a>
                        </td>
                        <td>
                            @item.Price
                            TL
                        </td>
                        <td>
                            @item.Category
                        </td>
                        <td>
                            @item.Barcode
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>




<div class="d-flex justify-content-between">

    <form asp-action="RemoveAllCarts" method="post">
        <button type="submit" class="btn btn-danger">Remove All Your Carts</button>
    </form>


    @if (Total != 0)
    {

        <div class="mb-4 mt-2 w-50">
            <form asp-action="Buy" method="post" class="card card-body w-100">
                <p>Total: @Total TL</p>
                <p>Dollar: @Math.Round(dollar, 2) USD</p>
                <p>Euro: @Math.Round(euro, 2) EUR</p>
                <p>Pound: @Math.Round(pound, 2) GBP</p>
                <button type="submit" class="btn btn-success w-100">Buy</button>
            </form>
        </div>
    }

</div>

Views/Shoppings/Index.cshtml
@model IEnumerable<SoftNET_Project.Models.Product>

@{

    ViewData["Title"] = "Shopping";
}
<div class="card mb-4 mt-2">
    <div class="card-body">
        <h1>SoftNET Market</h1>
    </div>
</div>


<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Products
    </div>
    <div class="card-body">
        <table id="sample_table" class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>
                        Product
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Category)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @{
                                bool isWishMine = false;
                            }
                            @foreach (var i in ViewBag.Wishlist)
                            {
                                if (i.Id == item.Id)
                                {
                                    isWishMine = true;
                                    break;
                                }
                            }
                            @if (isWishMine)
                            {
                                <form asp-action="RemoveWish" asp-route-id="@item.Id" method="post">
                                    <button class="btn btn-secondary"><i class="fa-solid fa-heart-crack"></i></button>
                                </form>
                            }
                            else
                            {
                                <form asp-action="AddWish" asp-route-id="@item.Id" method="post">
                                    <button type="submit" class="btn btn-danger"><i class="fa-solid fa-heart"></i></button>
                                </form>
                            }
                        </td>
                        <td>
                            <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.ProductName)</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price) TL
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Category)
                        </td>
                        <td>
                            @{
                                bool isCartMine = false;
                            }
                            @foreach (var i in ViewBag.Carts)
                            {
                                if (i.Id == item.Id)
                                {
                                    isCartMine = true;
                                    break;
                                }
                            }
                            @if (isCartMine)
                            {
                                <form class="ml-2" asp-action="RemoveCart" asp-route-id="@item.Id" method="post">
                                    <button class="btn btn-secondary">Remove from Carts</button>
                                </form>
                            }
                            else
                            {
                                <form class="ml-2" asp-action="AddCart" asp-route-id="@item.Id" method="post">
                                    <button type="submit" class="btn btn-success">Add to Carts</button>
                                </form>
                            }

                                
                                @*<a class="btn btn-success" asp-controller="Shoppings" asp-action="AddWish" asp-route-id="@item.Id" asp-route-type="Cart" >Buy</a>
                            <a class="btn btn-danger" asp-controller="Shoppings" asp-action="AddWish" asp-route-id="@item.Id" asp-route-type="Wishlist"><i class="fa-solid fa-heart"></i></a>*@
                            
                        </td>
                    </tr>
                }
            </tbody>

        </table>

    </div>
</div>

Views/Shoppings/Purchased.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Purchased";
}

<div class="card mb-4 mt-2">
    <div class="card-body">
        <h1>Purchased</h1>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Your Purchaseds
    </div>
    <div class="card-body">
        <table id="sample_table" class="table">
            <thead>
                <tr>
                    <th>
                        Product Name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Barcode
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.Purchaseds)
                {
                    <tr>
                        <td>
                            <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">@item.ProductName</a>
                        </td>
                        <td>
                            @item.Price
                            TL
                        </td>
                        <td>
                            @item.Category
                        </td>
                        <td>
                            @item.Barcode
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

Views/Shoppings/Wishlist.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Wishlist";
}

<div class="card mb-4 mt-2">
    <div class="card-body">
        <h1>Wishlist</h1>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Your Wishlist
    </div>
    <div class="card-body">
        <table id="sample_table" class="table">
            <thead>
                <tr>
                    <th>
                        Product Name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Category
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.Wishlist)
                {
                    <tr>
                        <td>
                            <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">@item.ProductName</a>
                        </td>
                        <td>
                            @item.Price
                            TL
                        </td>
                        <td>
                            @item.Category
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

<form asp-action="RemoveAllWishes" method="post" class="mb-4 d-flex justify-content-end">
    <button type="submit" class="btn btn-danger">Remove All Wishes</button>
</form>